# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe OperatingSystemsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # OperatingSystem. As you add validations to OperatingSystem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'MyOS'
    }
  end

  let(:invalid_attributes) do
    {
      name: ''
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OperatingSystemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      OperatingSystem.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      operating_system = OperatingSystem.create! valid_attributes
      get :edit, params: { id: operating_system.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new OperatingSystem' do
        expect do
          post :create, params: { operating_system: valid_attributes }, session: valid_session
        end.to change(OperatingSystem, :count).by(1)
      end

      it 'redirects to the created operating_system' do
        post :create, params: { operating_system: valid_attributes }, session: valid_session
        expect(response).to redirect_to(operating_systems_url)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { operating_system: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        {
          name: 'MyNewOS'
        }
      end

      it 'updates the requested operating_system' do
        operating_system = OperatingSystem.create! valid_attributes
        put :update, params: { id: operating_system.to_param, operating_system: new_attributes }, session: valid_session
        operating_system.reload
        expect(operating_system.name).to eq('MyNewOS')
      end

      it 'redirects to the operating_system' do
        operating_system = OperatingSystem.create! valid_attributes
        put :update, params: { id: operating_system.to_param, operating_system: valid_attributes }, session: valid_session
        expect(response).to redirect_to(operating_systems_url)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        operating_system = OperatingSystem.create! valid_attributes
        put :update, params: { id: operating_system.to_param, operating_system: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested operating_system' do
      operating_system = OperatingSystem.create! valid_attributes
      expect do
        delete :destroy, params: { id: operating_system.to_param }, session: valid_session
      end.to change(OperatingSystem, :count).by(-1)
    end

    it 'redirects to the operating_systems list' do
      operating_system = OperatingSystem.create! valid_attributes
      delete :destroy, params: { id: operating_system.to_param }, session: valid_session
      expect(response).to redirect_to(operating_systems_url)
    end
  end
end
